### ISSUE TITLE
Only short part of Blog gets posted

### ISSUE THREAD

**Issue by MaxHillebrand** [piraces/rsslay#26]
This is a lovely software, thanks!

When reposting a blog article, it only shows the first couple lines, not the entire post.

Example: note154gjecmpaqgffxg2ukdkf5qu94lpgfc9363e2q8slwpc5azh9a4sdv0x3p

Is it possible to also post the entire blog in the note?

**Comment by piraces** [comment]
Thanks @MaxHillebrand for reaching out! 
Currently `rsslay` is trimming the description text to a max of 250 characters (+ title, comments link and official link).
I think we can adjust this limitation to provide either the full text or increase the limit... something configurable.

I'm currently checking some default restrictions of common relays:
- `nostream`: 1MB
- `nostr-rs-relay`: 128KB
- `me.untethr.nostr-relay`: 1048576 characters
- `strfry`: 65536 bytes

So I think you are right and we can increase and attempt to publish the whole post if it's not enourmous... Will implement and monitor it for issues!

**Comment by piraces** [comment]
Hi @MaxHillebrand , I have implemented a new configuration setting via environment variable `MAX_CONTENT_LENGTH` which allows you to set the maximum length in characters to limit the content of the rss feeds. For the main instance I have set this option to 5000 chars, which I will be monitoring and I think it's a good average... If the content exceeds the 5000 chars you may go to the original blog post to finish read it.

Let me know what you think!

P.S. To be released in version v0.4.4

**Comment by MaxHillebrand** [comment]
Thanks, this seems to be exactly what I was looking for.

Well done on the swift implementation!
