### ISSUE TITLE
Question about ReplayEvents

### ISSUE THREAD

**Issue by zach030** [piraces/rsslay#39]
The project is awesome! 
I just read the code and confused about the usage of AttemptReplayEvents. 
What's the purpose of replay events to other relays, just as the mirror relay or other reasons?

**Comment by piraces** [comment]
Thank you very much @zach030 !
Yes, actuallly the usage of `AttemptReplayEvents` is to send the events to other relays of confidence to attempt to make the events and the profile more reachable (they are just mirror relays)...

Maybe in the future with other implementations we can avoid that, but nowadays its needed.
Did this explanation answer your question?

**Comment by zach030** [comment]
> Thank you very much @zach030 ! Yes, actually the usage of `AttemptReplayEvents` is to send the events to other relays of confidence to attempt to make the events and the profile more reachable (they are just mirror relays)...
> 
> Maybe in the future with other implementations we can avoid that, but nowadays its needed. Did this explanation answer your question?

Thanks, I got that. Is it better to add them to the README or they are hidden in the code

**Comment by piraces** [comment]
You're right... Will add to the README of the project and documentation 🤙

**Comment by piraces** [comment]
Added to wiki and README to inform all users 👍
