### ISSUE TITLE
NIP-05 registration sends wrong domain

### ISSUE THREAD

**Issue by mdebus** [piraces/rsslay#71]
If I enable NIP-05 auto registration, clients see the wrong domain name (rsslay.nostr.moe), even though MAIN_DOMAIN_NAME is set correctly.

Steps to reproduce:
- add wss://rsslay.data.haus to your relays
- follow npub1004j8jctfepp2kmwarukdkhk3rme28zj4sq67ftny2yzaxfltuwqcdjdnv  (news feed)
- view this profile in Amethyst or primal.net

**Comment by piraces** [comment]
Arrgh... Sorry for that... Will review it ASAP. Thanks for reporting @mdebus

**Comment by piraces** [comment]
The fix will be released with v0.5.0. Thank you!
