### ISSUE TITLE
Replay to relays does not work anymore in 0.4.9 

### ISSUE THREAD

**Issue by mdebus** [piraces/rsslay#72]
No matter which relays I add to RELAYS_TO_PUBLISH_TO.

Log:

```
rsslay          | [go-nostr][info] 2023/05/16 09:40:12 {wss://nos.lol} error writing ping: use of closed network connection; closing websocket
rsslay          | [go-nostr][info] 2023/05/16 09:40:17 {wss://nostr.data.haus} error writing ping: use of closed network connection; closing websocket
```

**Comment by piraces** [comment]
Thank you for reporting this @mdebus ! Will review this issue as soon as possible... 👍

**Comment by piraces** [comment]
Hello @mdebus , I have released a new version v0.5.0 with a potential fix for this...
I'm now connecting before replaying any event ensuring websockets are not closed and ready.
This has been running for a while in the rsslay.nostr.moe instance and appears to be ok.

The only problem I have seen it's when the `created_at` field:
```
[INFO] Failed to replay event to wss://relay.nostr.band with error: msg: invalid: created_at is not acceptable (-1h, +30min)
```

But I think we can do nothing with this types of checking (the `created_at` date must be not altered from the source).

Please let me know how this fix works for you. Thanks!

**Comment by mdebus** [comment]
Hello @piraces! I'm running 0.5.0 now for 16 hours but I see no entries for replaying at all in the logs. 

Log level is "info", so it should be shown, right?

**Comment by piraces** [comment]
Yes... normally success messages will be on "DEBUG" level, while when a problem occurs it must be on "WARN" or "ERROR".
Happy to see this appears to be solved! will let this issue opened for a while nevertheless 👍

**Comment by mdebus** [comment]
Thanks a lot! Will report if the problem stills occurs.

**Comment by mdebus** [comment]
One question though: Is the replaying part only triggered if I actually use rsslay as an relay in a client, or is is working independently. 

Just asking myself if I need both nostr.data.haus and rsslay.data.haus in my relay list.

**Comment by piraces** [comment]
> One question though: Is the replaying part only triggered if I actually use rsslay as an relay in a client, or is is working independently?
> 
> Just asking myself if I need both nostr.data.haus and rsslay.data.haus in my relay list.

Replaying only occurs when a client requests feed notes from rsslay, then rsslay triggers the replay process to make it available to other relays.
This process happen independently of you having the replaying servers on your relay list (`nostr.data.haus` in this case), but you actually need the rsslay instance in your relay list to trigger that "replay part".

Maybe in the future we can improve this process...

**Comment by mdebus** [comment]
Ok, got it. Thanks for clarifying!
